import { getCurrentJalaliDate } from '../utils/date';
import { loadLocalValue, saveLocalValue } from './localStore';

const DEMO_MARKER = 'demoDataVersion';
const DEMO_PREFIX = 'demo-';
const now = () => new Date().toISOString();
const attachment = { id: 'demo-attachment-1', fileName: 'گزارش-نمایشی.pdf', fileSizeBytes: 182000, fileExtension: 'pdf', uploadDate: getCurrentJalaliDate(), uploadedBy: 'اطلاعات نمایشی', downloadUrl: '#' };

// این داده عمداً از همان collectionهای سرویس‌ها استفاده می‌کند؛ هیچ مسیر
// موازی یا API خیالی برای حالت دمو ساخته نشده است.
const createDemo = () => {
  const date = getCurrentJalaliDate();
  const proposal = { id: 'demo-proposal-1', proposalNumber: 'پیشنهاد-نمایشی-۱', title: 'تکمیل داشبورد پایش مصوبات', proposerName: 'مهندس سارا نیک‌نام', proposerUserId: 'user-9', proposerDepartmentId: 'dept-1', proposerDepartmentName: 'اداره کل فناوری اطلاعات و ارتباطات', presenterName: 'مهندس سارا نیک‌نام', description: 'پیشنهاد نمونه برای نمایش گردش کامل جلسات و مصوبات.', rationale: 'بهبود شفافیت پیگیری تصمیم‌ها', dateJalali: date, attachments: [attachment], status: 'CONVERTED_TO_AGENDA', assignedMeetingId: 'demo-meeting-1', assignedMeetingTitle: 'جلسه راهبری تحول دیجیتال', createdAt: now(), updatedAt: now(), source: 'MANUAL', history: [{ id: 'demo-proposal-history-1', action: 'تأیید نهایی و افزوده‌شدن به دستور جلسه', actorName: 'دبیر جلسه', actorRole: 'SECRETARY', dateJalali: date, timeString: '۱۰:۳۰', notes: 'اطلاعات نمایشی' }] };
  const meeting = { id: 'demo-meeting-1', meetingNumber: 'جلسه-نمایشی-۱', title: 'جلسه راهبری تحول دیجیتال', type: 'PROJECT_STEERING', dateJalali: date, startTime: '۰۹:۰۰', endTime: '۱۰:۳۰', location: 'سالن جلسات مرکزی', organizerId: 'user-2', organizerName: 'مهندس پوریا حسینی', secretaryId: 'user-8', secretaryName: 'مهندس جواد صادقی', departmentId: 'dept-1', departmentName: 'اداره کل فناوری اطلاعات و ارتباطات', status: 'HELD', description: 'جلسه نمایشی با یک دستور کار و مصوبه مرتبط.', minutesSummary: 'تصمیم به اجرای نسخه نمایشی و پایش پیشرفت گرفته شد.', members: [{ userId: 'user-2', fullName: 'مهندس پوریا حسینی', roleTitle: 'مدیر کل فناوری اطلاعات و تحول دیجیتال', departmentName: 'اداره کل فناوری اطلاعات و ارتباطات', attendanceType: 'ORGANIZER', presenceStatus: 'PRESENT' }, { userId: 'user-8', fullName: 'مهندس جواد صادقی', roleTitle: 'دبیر شورای راهبری و مدیر PMO', departmentName: 'مدیریت طرح و پشتیبانی پروژه‌ها', attendanceType: 'SECRETARY', presenceStatus: 'PRESENT' }], agendaItems: [{ id: 'demo-agenda-1', order: 1, rowNumber: 1, title: proposal.title, presenter: proposal.presenterName, presenterName: proposal.presenterName, startTime: '۰۹:۰۰', endTime: '۱۰:۰۰', estimatedMinutes: 60, allocatedMinutes: 60, isDiscussed: true, status: 'APPROVED', description: proposal.description, sourceProposalId: proposal.id, attachments: [attachment] }], history: [{ id: 'demo-meeting-history-1', action: 'نهایی‌سازی صورت‌جلسه', actorName: 'دبیر جلسه', actorRole: 'SECRETARY', timestampJalali: date, timeString: '۱۱:۰۰', details: 'اطلاعات نمایشی' }], resolutionsCount: 1, attachments: [attachment], createdAt: now(), updatedAt: now() };
  const resolution = { id: 'demo-resolution-1', resolutionNumber: 'مصوبه-نمایشی-۱', meetingResolutionNumber: '۱', meetingId: meeting.id, meetingTitle: meeting.title, meetingNumber: meeting.meetingNumber, agendaItemId: 'demo-agenda-1', agendaItemTitle: proposal.title, topicTitle: 'اجرای داشبورد پایش مصوبات', proposerName: proposal.proposerName, proposerDepartment: proposal.proposerDepartmentName, requestDescription: 'نسخه نمایشی داشبورد تا پایان هفته آماده و گزارش پیشرفت ثبت شود.', reviewResultNotes: 'تصویب شد.', approvalStatus: 'APPROVED', executionDescription: 'تکمیل اجزای داشبورد و گزارش وضعیت.', mainResponsibleUserId: 'user-9', mainResponsibleName: 'مهندس سارا نیک‌نام', responsibleDepartmentId: 'dept-1', responsibleDepartmentName: proposal.proposerDepartmentName, assignedDateJalali: date, deadlineJalali: date, priority: 'HIGH', executionStatus: 'IN_PROGRESS', referrals: [{ id: 'demo-referral-1', targetType: 'USER', targetId: 'user-9', targetName: 'مهندس سارا نیک‌نام', instructions: 'گزارش پیشرفت را ثبت کنید.', referredAt: now(), referredByName: 'مسئول دفتر' }], verificationConfig: { requiresVerification: true, mode: 'SEQUENTIAL', currentStepIndex: 0, steps: [{ stepNumber: 1, approverUserId: 'user-15', approverName: 'دکتر وحید سلیمانی', approverTitle: 'ناظر و بازرس ارشد سازمان', status: 'PENDING' }] }, attachments: [attachment], progressPercent: 60, lastAction: 'نسخه نمایشی آماده بازبینی است.', progressReports: [{ id: 'demo-progress-1', taskId: 'demo-task-1', resolutionId: 'demo-resolution-1', reporterUserId: 'user-9', reporterName: 'مهندس سارا نیک‌نام', progressPercent: 60, status: 'IN_PROGRESS', actionDescription: 'پیاده‌سازی داشبورد و کنترل نقش‌ها انجام شد.', reportDateJalali: date, reportTimeString: '۱۴:۰۰', attachments: [attachment] }], createdAt: now(), notifiedAt: now(), notifiedDateJalali: date, notifiedTimeString: '۱۲:۰۰', notifiedByUserId: 'user-office', notifiedByName: 'مسئول دفتر', notificationLetterNumber: 'ابلاغ-نمایشی-۱' };
  const task = { id: 'demo-task-1', resolutionId: resolution.id, resolutionNumber: resolution.resolutionNumber, resolutionTitle: resolution.topicTitle, meetingId: meeting.id, meetingTitle: meeting.title, assignedToUserId: 'user-9', assignedToName: 'مهندس سارا نیک‌نام', departmentId: 'dept-1', departmentName: proposal.proposerDepartmentName, referralDateJalali: date, deadlineJalali: date, priority: 'HIGH', status: 'IN_PROGRESS', requiresVerification: true, verificationCurrentStepTitle: 'صحـه‌گذاری ناظر', instructions: 'نسخه نمایشی را تکمیل و گزارش کنید.', progressPercent: 60, lastAction: 'در انتظار تکمیل گزارش', progressReports: resolution.progressReports, attachments: [attachment] };
  const approval = { id: 'demo-approval-1', resolutionId: resolution.id, resolutionNumber: resolution.resolutionNumber, resolutionTitle: resolution.topicTitle, meetingTitle: meeting.title, responsibleName: task.assignedToName, responsibleDepartment: task.departmentName, completedDateJalali: date, submittedForApprovalDateJalali: date, stepNumber: 1, totalSteps: 1, stepTitle: 'صحـه‌گذاری ناظر', assignedApproverId: 'user-15', status: 'PENDING', completionReport: 'گزارش پیشرفت نمایشی با پیوست ثبت شده است.', attachments: [attachment] };
  const logs = ['ثبت پیشنهاد', 'بررسی مدیرعامل', 'برگزاری جلسه', 'ثبت مصوبه', 'ابلاغ و ارجاع', 'ثبت گزارش پیشرفت'].map((action, index) => ({ id: `demo-log-${index + 1}`, targetType: index < 3 ? 'MEETING' : 'RESOLUTION', targetId: index < 3 ? meeting.id : resolution.id, action, actorName: 'اطلاعات نمایشی', actorRole: 'SYSTEM', timestampJalali: date, timeString: `۰${9 + index}:۰۰`, details: 'اطلاعات نمایشی', badgeColor: 'teal' }));
  return { proposals: [proposal], meetings: [meeting], resolutions: [resolution], tasks: [task], approvals: [approval], activityLogs: logs, notifications: [{ id: 'demo-notification-1', recipientUserId: 'user-9', title: 'ارجاع مصوبه نمایشی', message: 'گزارش پیشرفت خود را ثبت کنید.', dateJalali: date, timeString: '۱۲:۰۰', isRead: false, type: 'ASSIGNMENT', targetRoute: 'tasks', targetResolutionId: resolution.id }], resolutionNotices: [{ id: 'demo-notice-1', noticeNumber: 'ابلاغ-نمایشی-۱', resolutionId: resolution.id, resolutionNumber: resolution.resolutionNumber, meetingId: meeting.id, dateJalali: date, recipientName: task.assignedToName, recipientDepartment: task.departmentName, text: 'ابلاغ نمایشی اجرای مصوبه.', deadlineJalali: date, attachmentIds: [attachment.id], status: 'SENT', sentAt: now(), createdByUserId: 'user-office', notificationLetterNumber: 'ابلاغ-نمایشی-۱', secretaryUserId: 'user-8', secretaryName: meeting.secretaryName }], resolutionFollowUps: [{ id: 'demo-followup-1', resolutionId: resolution.id, resolutionNumber: resolution.resolutionNumber, resolutionTitle: resolution.topicTitle, followUpDateJalali: date, text: 'پیگیری نمایشی از مجری', attachments: [], createdByUserId: 'user-office', createdByName: 'مسئول دفتر', createdAt: now() }], archiveFolders: [{ id: 'demo-folder-1', name: 'بایگانی نمایشی', description: 'پرونده‌های مسیر دمو', scope: 'ORGANIZATION', createdByUserId: 'user-admin', createdByName: 'مدیر سیستم', createdAt: now() }], archiveItems: [] };
};

const keys = ['proposals', 'meetings', 'resolutions', 'tasks', 'approvals', 'activityLogs', 'notifications', 'resolutionNotices', 'resolutionFollowUps', 'archiveFolders', 'archiveItems'] as const;

export const loadDemoData = () => { const demo = createDemo() as Record<string, unknown[]>; keys.forEach((key) => { const current = loadLocalValue<unknown[]>(key, []); const withoutDemo = current.filter((item) => !(item && typeof item === 'object' && String((item as { id?: string }).id || '').startsWith(DEMO_PREFIX))); saveLocalValue(key, [...withoutDemo, ...demo[key]]); }); saveLocalValue(DEMO_MARKER, { version: 1, loadedAt: now() }); };
export const resetDemoData = () => { keys.forEach((key) => saveLocalValue(key, loadLocalValue<unknown[]>(key, []).filter((item) => !(item && typeof item === 'object' && String((item as { id?: string }).id || '').startsWith(DEMO_PREFIX))))); saveLocalValue(DEMO_MARKER, null); };
export const hasDemoData = () => loadLocalValue<unknown[]>('meetings', []).some((item) => item && typeof item === 'object' && String((item as { id?: string }).id || '').startsWith(DEMO_PREFIX));
